# Generated by Django 6.0.3 on 2026-03-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_available_from_products_available_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Products'},
        ),
    ]
