# Generated by Django 6.0.2 on 2026-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(default=0, help_text='e.g. per kg, per bunch, each', max_length=50),
        ),
    ]
