# Generated by Django 6.0.3 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='best_before',
            field=models.DateField(blank=True, help_text='Best before / use-by date', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_surplus',
            field=models.BooleanField(default=False, help_text='Whether this product is on a surplus deal'),
        ),
        migrations.AddField(
            model_name='products',
            name='surplus_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted surplus price', max_digits=8, null=True),
        ),
    ]
