# Generated by Django 6.0.2 on 2026-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('bakery', 'Bakery'), ('preserves', 'Preserves'), ('seasonal_speciality', 'Seasonal Specialties')], default='other', max_length=50),
        ),
    ]
