# Generated by Django 6.0.3 on 2026-05-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_category'),
        ('products', '0007_products_low_stock_threshold'),
    ]

    operations = [
    ]
