# Generated by Django 6.0.2 on 2026-05-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20260507_0954'),
        ('products', '0008_merge_20260507_0957'),
    ]

    operations = [
    ]
