# Generated by Django 6.0.2 on 2026-05-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_accounts_customer_type'),
        ('products', '0009_merge_20260507_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Recipe overview and story')),
                ('ingredients', models.TextField(help_text='List ingredients, one per line or comma-separated')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], help_text='Seasonal tag for organization', max_length=20)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('serves', models.CharField(blank=True, help_text='Number of servings', max_length=100)),
                ('is_published', models.BooleanField(default=True, help_text='Whether recipe is visible to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.producers')),
                ('products', models.ManyToManyField(blank=True, help_text='Link to products used in this recipe', related_name='recipes', to='products.products')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
