# Generated by Django 6.0.3 on 2026-03-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_producers_alter_accounts_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='producer_images/'),
        ),
        migrations.AddField(
            model_name='producers',
            name='store_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
