# Generated by Django 6.0.3 on 2026-03-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_producers_business_image_producers_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='producer_banners/'),
        ),
        migrations.AddField(
            model_name='producers',
            name='certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producers',
            name='collection_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producers',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producers',
            name='farm_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producers',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='producers',
            name='store_description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
