# Generated by Django 6.0.3 on 2026-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_producers_banner_image_producers_certifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='producers',
            options={'verbose_name_plural': 'Producers'},
        ),
        migrations.AlterField(
            model_name='producers',
            name='description',
            field=models.CharField(help_text='Short tagline for your business', max_length=100),
        ),
    ]
