# Generated by Django 6.0.3 on 2026-03-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_options_alter_producers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude for map pin', null=True),
        ),
        migrations.AddField(
            model_name='producers',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude for map pin', null=True),
        ),
    ]
