# Generated by Django 6.0.3 on 2026-03-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_producers_latitude_producers_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
