# Generated by Django 6.0.4 on 2026-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('community_group', 'Community Group'), ('restaurant', 'Restaurant')], default='individual', max_length=30),
        ),
    ]
