# Generated by Django 6.0.3 on 2026-05-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accounts_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('restaurant', 'Restaurant'), ('community_group', 'Community Group')], default='individual', max_length=30),
        ),
    ]
