# Generated by Django 6.0.3 on 2026-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_accounts_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='customer_type',
            field=models.CharField(choices=[('community_group', 'Community Group'), ('restaurant', 'Restaurant'), ('individual', 'Individual')], default='individual', max_length=30),
        ),
    ]
