# Generated by Django 6.0.2 on 2026-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_accounts_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='customer_type',
            field=models.CharField(choices=[('community_group', 'Community Group'), ('individual', 'Individual'), ('restaurant', 'Restaurant')], default='individual', max_length=30),
        ),
    ]
