# Generated by Django 6.0.2 on 2026-03-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_accounts_options_alter_producers_options_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_number', models.CharField(blank=True, default='', max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=100)),
                ('sort_code', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producer_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.orders')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.producers')),
                ('weekly_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.weeklypayment')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
