# Generated by Django 6.0.3 on 2026-03-27 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_options_alter_producers_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weeklypayment',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_payments', to='accounts.producers'),
        ),
        migrations.AddField(
            model_name='weeklypayment',
            name='week_starting',
            field=models.DateField(blank=True, null=True),
        ),
    ]
