# Generated by Django 6.0.3 on 2026-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_delivery_address_orders_fulfillment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
