# Generated by Django 6.0.3 on 2026-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
