# Generated by Django 6.0.4 on 2026-05-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_is_recurring_orders_recurring_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='orders',
            name='bulk_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
