# Generated by Django 6.0.4 on 2026-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_is_recurring_orders_bulk_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='special_delivery_requirements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
